# Generated by Django 4.0.5 on 2022-07-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('fathername', models.CharField(max_length=255)),
                ('dateofbirth', models.CharField(max_length=255)),
                ('nrcno', models.CharField(max_length=255)),
                ('contactno', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('pAddress', models.CharField(max_length=255)),
                ('edu', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
            ],
        ),
    ]
